sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
env:
  - VERSION=1.0.0-SNAPSHOT ARCHETYPE_VERSION=5.3.0-SNAPSHOT GFW_BRANCH=master ARCHETYPE_BRANCH=master TARGET_PROJECT=target-project
  - VERSION=1.0.0-SNAPSHOT ARCHETYPE_VERSION=5.2.1-SNAPSHOT GFW_BRANCH=5.2.x ARCHETYPE_BRANCH=5.2.x TARGET_PROJECT=target-project
  - VERSION=1.0.0-SNAPSHOT ARCHETYPE_VERSION=5.2.0.RELEASE GFW_BRANCH=5.2.0.RELEASE ARCHETYPE_BRANCH=5.2.0.RELEASE TARGET_PROJECT=target-project
  - VERSION=1.0.0-SNAPSHOT ARCHETYPE_VERSION=5.1.2-SNAPSHOT GFW_BRANCH=5.1.x ARCHETYPE_BRANCH=5.1.x TARGET_PROJECT=target-project
  - VERSION=1.0.0-SNAPSHOT ARCHETYPE_VERSION=5.1.1.RELEASE GFW_BRANCH=5.1.1.RELEASE ARCHETYPE_BRANCH=5.1.1.RELEASE TARGET_PROJECT=target-project
  - VERSION=1.0.0-SNAPSHOT ARCHETYPE_VERSION=5.1.0.RELEASE GFW_BRANCH=5.1.0.RELEASE ARCHETYPE_BRANCH=5.1.0.RELEASE TARGET_PROJECT=target-project

install:


before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CARGO_DAEMON_WEBAPP_VERSION=1.4.17
  - mvn dependency:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:${CARGO_DAEMON_WEBAPP_VERSION}:war -DoutputDirectory=./
  - java -jar ./cargo-daemon-webapp-${CARGO_DAEMON_WEBAPP_VERSION}.war &

script: 
  - cd $HOME/.m2
  - ll
